// src/components/blog/AISection.tsx
"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Sparkles, Bot, Send, ChevronDown, ChevronUp, Loader2 } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";

export function AISection() {
  const [isOpen, setIsOpen] = useState(true);
  const [summary, setSummary] = useState("");
  const [question, setQuestion] = useState("");
  const [conversation, setConversation] = useState<{ user: string; ai: string }[]>([]);
  const [isLoadingSummary, setIsLoadingSummary] = useState(false);
  const [isLoadingQuestion, setIsLoadingQuestion] = useState(false);

  const handleGenerateSummary = () => {
    setIsLoadingSummary(true);
    setSummary("");
    // Dummy logic
    setTimeout(() => {
      setSummary("This is a dummy AI-generated summary of the blog post, highlighting the key concepts and main takeaways in a concise manner.");
      setIsLoadingSummary(false);
    }, 1500);
  };

  const handleAskQuestion = () => {
    if (!question.trim()) return;
    setIsLoadingQuestion(true);
    // Dummy logic
    setTimeout(() => {
      setConversation([
        ...conversation,
        {
          user: question,
          ai: "This is a dummy answer to your question. In a real implementation, this would be generated by an AI model based on the blog content.",
        },
      ]);
      setQuestion("");
      setIsLoadingQuestion(false);
    }, 1000);
  };

  return (
    <div className="relative rounded-2xl border border-purple-500/30 bg-slate-900/50 p-6 backdrop-blur-xl group">
      <div className="absolute -inset-px rounded-2xl bg-gradient-to-r from-purple-500/20 via-cyan-500/20 to-purple-500/20 opacity-0 group-hover:opacity-100 transition-opacity duration-300"/>
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="flex w-full items-center justify-between font-headline text-xl text-purple-300"
      >
        <div className="flex items-center gap-3">
          <Sparkles className="h-6 w-6" />
          AI Tools
        </div>
        {isOpen ? <ChevronUp /> : <ChevronDown />}
      </button>

      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ height: 0, opacity: 0, marginTop: 0 }}
            animate={{ height: "auto", opacity: 1, marginTop: "1.5rem" }}
            exit={{ height: 0, opacity: 0, marginTop: 0 }}
            transition={{ duration: 0.4, ease: "easeInOut" }}
            className="overflow-hidden"
          >
            <div className="space-y-6">
              {/* AI Summary */}
              <div>
                <h4 className="font-semibold text-purple-400 mb-3">AI Summary</h4>
                <Button onClick={handleGenerateSummary} disabled={isLoadingSummary} size="sm" className="bg-purple-600/80 hover:bg-purple-600 text-white">
                  {isLoadingSummary ? <Loader2 className="mr-2 h-4 w-4 animate-spin"/> : null}
                  {isLoadingSummary ? "Generating..." : "Generate Summary"}
                </Button>
                {summary && <p className="mt-4 text-sm text-slate-300 border-l-2 border-purple-400/50 pl-4">{summary}</p>}
              </div>

              {/* AI Q&A */}
              <div>
                <h4 className="font-semibold text-purple-400 mb-3">Ask a Question</h4>
                <div className="space-y-4">
                  {conversation.map((entry, i) => (
                    <div key={i} className="text-sm">
                      <p className="font-semibold text-cyan-300">You: {entry.user}</p>
                      <p className="text-slate-300 mt-1">AI: {entry.ai}</p>
                    </div>
                  ))}
                   {isLoadingQuestion && (
                      <div className="flex items-center gap-2">
                        <Bot size={16} className="text-cyan-400"/>
                        <span className="text-sm text-slate-400">Thinking...</span>
                      </div>
                    )}
                </div>
                <div className="mt-4 flex items-center gap-2">
                  <Textarea
                    value={question}
                    onChange={(e) => setQuestion(e.target.value)}
                    placeholder="Ask anything about this blog..."
                    onKeyDown={(e) => {
                      if (e.key === 'Enter' && !e.shiftKey) {
                        e.preventDefault();
                        handleAskQuestion();
                      }
                    }}
                    className="bg-slate-800/60 border-purple-500/40 text-white"
                    rows={1}
                    disabled={isLoadingQuestion}
                  />
                  <Button onClick={handleAskQuestion} disabled={isLoadingQuestion || !question.trim()} size="icon" className="bg-cyan-600/80 hover:bg-cyan-600 text-white flex-shrink-0">
                    <Send />
                  </Button>
                </div>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
